script:
  - docker build -t dohli .
  - docker run -d --rm -e PORT=8080 -e REDIS_URL=redis://localhost dohli /web
  - docker run -d --rm -e REDIS_URL=redis://localhost dohli /worker
  - echo AAABAAABAAAAAAAABGlwdjYGZ29vZ2xlA2NvbQAAAQAB | base64 -d > /tmp/request
  - curl -f -o /dev/null --data-binary @/tmp/request http://localhost:8080/dns-query

services:
  - docker
  - redis-server