script:
  - docker network create dohli
  - docker run -d --rm --network dohli --name redis redis:alpine
  - docker build -t dohli .
  - docker run -d --rm --network dohli -p 8080:8080 -e PORT=8080 -e REDIS_URL=redis://redis dohli /web
  - docker run -d --rm --network dohli -e REDIS_URL=redis://redis dohli /worker
  - sleep 2
  - echo AAABAAABAAAAAAAABGlwdjYGZ29vZ2xlA2NvbQAAAQAB | base64 -d > /tmp/request
  - curl -f -o /dev/null --data-binary @/tmp/request http://localhost:8080/dns-query

services:
  - docker

deploy:
  provider: heroku
  api_key:
    secure: nGaFMKxAFtckeYkvVR4sp0cDIbQs+SJJxDoNSfVKOIdji8fHHGiz75jkaVBWXZvndWaKvCLd3yY/0xOfMy5peqg1LG/AjkP4/WrZ7yna7flslew0skmngknMvQ8CpO2ElXjVg1lBJgUtAhKJH72jLZwpaXu88HgDPHaCEpdNDQypMxG2+TR+FJHl+BYZoz52nQybtm/i7PhSmZ5+WWIY8osyADkGKaSyZ4AHV2WiyMwaAWlailEkm52qjQPGZRgPXpjdvL8MUv5k7v5d+s8mHTLCKdzLyvqqsRdqjs2cTch1udDi+KU/QzTh2ZRSh5r7YLP7tKTKqqlS0Vmj14rQxCpZiaajanacy8M26W0OxfrxGf+kxulo9x6eY6IjUR45sbZIhZCrPBiRuBDB91mIMdn1GMbrO1KWlZYL4VaIZQIFlvtCdoLvTrPEa33zrjXSVyyGMw9OGeMjNv/ErAiWLDe1S0lqQGiU026yBbqpvzp+LXFZihdiPT0up1FETr9ozxcV+W9uScYowkS/ySYri+NkwHuVaGiQTSCjHP2ZVwtdN3xrQYSgRah2bHAC/khel9bHJQNnbBQNy9v+HyOUKCL7Bx14f1h4j1oOP4qxiwcaPePuySkQMGUyuinltjINx/kLEjYYaQ96rBCtMJpxSV61my1tvrc/1643Do1f8BI=
  on:
    branch: master